language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode

gemfile:
  - gemfiles/default-with-activesupport.gemfile
  - gemfiles/json.gemfile
  - gemfiles/yajl.gemfile

matrix:
  exclude:
    - rvm: jruby-19mode
      gemfile: gemfiles/yajl.gemfile

sudo: false

branches:
  only:
    - master

addons:
  code_climate: 27c67395673ed8b89ce84de4c89fe0cc9f397147daaae4e583796ef9f5b67640
